"""
"AI Security Analyst" explanation for a blocked/flagged request. Same
additive-not-required design as the NIDS project: real Anthropic API
call if `ANTHROPIC_API_KEY` is set, otherwise a genuine structured
offline template built from the same data (not a stub).
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional

try:
    import httpx
except ImportError:  # pragma: no cover
    httpx = None

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
MODEL = "claude-sonnet-4-6"


def _offline_explanation(request: Dict[str, Any], predicted_class: str,
                          rule_matches: List[Dict[str, Any]]) -> str:
    parts = [
        f"The request `{request.get('method', 'GET')} {request.get('path', '/')}"
        f"{'?' + request.get('query_string') if request.get('query_string') else ''}` "
        f"from {request.get('client_ip', 'an unknown client')} was classified as "
        f"**{predicted_class}** by the ML content classifier."
    ]
    if rule_matches:
        names = "; ".join(m["name"] for m in rule_matches)
        parts.append(f"It also matched {len(rule_matches)} signature rule(s): {names}.")
    else:
        parts.append("No signature rule matched -- this verdict rests on the ML classifier alone.")

    if predicted_class == "SQLI":
        parts.append(
            "SQL injection payloads attempt to alter the intended database "
            "query -- typically by closing a quoted string and appending "
            "additional SQL logic (a tautology like OR 1=1, or a UNION "
            "SELECT to pull data from other tables)."
        )
    elif predicted_class == "XSS":
        parts.append(
            "Cross-site scripting payloads attempt to have the victim's "
            "browser execute attacker-supplied script, often to steal "
            "session cookies or perform actions as the logged-in user."
        )
    elif predicted_class == "PATH_TRAVERSAL":
        parts.append(
            "Path traversal payloads attempt to escape the web root using "
            "../ sequences to read arbitrary files on the server."
        )
    elif predicted_class == "COMMAND_INJECTION":
        parts.append(
            "Command injection payloads attempt to have the server execute "
            "an OS shell command, usually chained onto a parameter with "
            "shell metacharacters (;, |, $(), backticks)."
        )
    elif predicted_class == "SCANNER_RECON":
        parts.append(
            "This looks like automated reconnaissance -- a known scanning "
            "tool or a probe of a well-known sensitive path -- rather than "
            "a targeted exploit attempt."
        )

    parts.append(
        "(Generated by ShieldWAF's offline rule-based explainer -- set "
        "ANTHROPIC_API_KEY to enable natural-language AI Security Analyst "
        "explanations instead.)"
    )
    return " ".join(parts)


def explain_request(request: Dict[str, Any], predicted_class: str,
                     rule_matches: List[Dict[str, Any]]) -> Dict[str, Any]:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key or httpx is None:
        return {"source": "offline_template", "explanation": _offline_explanation(request, predicted_class, rule_matches)}

    prompt = (
        "You are a SOC analyst assistant for a web application firewall. "
        "In 3-4 concise sentences, explain to a junior analyst why this "
        "HTTP request was flagged, in plain English, referencing the "
        f"concrete request content. Request: {request}. Predicted class: "
        f"{predicted_class}. Rule matches: {rule_matches}."
    )
    try:
        resp = httpx.post(
            ANTHROPIC_API_URL,
            headers={"x-api-key": api_key, "anthropic-version": "2023-06-01", "content-type": "application/json"},
            json={"model": MODEL, "max_tokens": 300, "messages": [{"role": "user", "content": prompt}]},
            timeout=10.0,
        )
        resp.raise_for_status()
        data = resp.json()
        text = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")
        return {"source": "anthropic_api", "explanation": text.strip() or _offline_explanation(request, predicted_class, rule_matches)}
    except Exception as exc:
        return {
            "source": "offline_template_after_api_error",
            "explanation": _offline_explanation(request, predicted_class, rule_matches),
            "api_error": str(exc),
        }
